/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Camera.glb --transform 
Files: Camera.glb [6.98KB] > /Users/quan/cursor/fellou_try_v6/Camera-transformed.glb [5KB] (28%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Camera-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera name="Camera" makeDefault={false} far={10000} near={0.1} fov={25.361} position={[13.037, 2.624, 23.379]} rotation={[0.318, 0.562, -0.051]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Camera-transformed.glb')
