/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LOST_cut2_v6.glb --transform 
Files: LOST_cut2_v6.glb [923.25MB] > /Users/quan/cursor/fellou_try_v6/LOST_cut2_v6-transformed.glb [22.31MB] (98%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/LOST_cut2_v6-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Scenes_B_00100" position={[0.609, 14.249, -5.731]} rotation={[-0.018, 0.004, 2.077]} scale={0.026}>
          <mesh name="網格003" geometry={nodes.網格003.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_1" geometry={nodes.網格003_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_2" geometry={nodes.網格003_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_3" geometry={nodes.網格003_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_4" geometry={nodes.網格003_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_5" geometry={nodes.網格003_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_6" geometry={nodes.網格003_6.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_7" geometry={nodes.網格003_7.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_8" geometry={nodes.網格003_8.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_9" geometry={nodes.網格003_9.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Scenes_B_0023" position={[11.171, 3.182, 11.142]} rotation={[-1.132, -0.089, -2.546]} scale={0.039}>
          <mesh name="網格002" geometry={nodes.網格002.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_1" geometry={nodes.網格002_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_2" geometry={nodes.網格002_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_3" geometry={nodes.網格002_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_4" geometry={nodes.網格002_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_5" geometry={nodes.網格002_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_6" geometry={nodes.網格002_6.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_7" geometry={nodes.網格002_7.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_8" geometry={nodes.網格002_8.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格002_9" geometry={nodes.網格002_9.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Scenes_B_00100001" position={[0.609, 0.7, 6.831]} rotation={[-0.024, 0, 2.269]} scale={[0.026, 0.026, 0.016]}>
          <mesh name="網格001" geometry={nodes.網格001.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_1" geometry={nodes.網格001_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_2" geometry={nodes.網格001_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_3" geometry={nodes.網格001_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_4" geometry={nodes.網格001_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_5" geometry={nodes.網格001_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_6" geometry={nodes.網格001_6.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_7" geometry={nodes.網格001_7.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_8" geometry={nodes.網格001_8.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格001_9" geometry={nodes.網格001_9.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="素白艺术™_-_subycnvip" geometry={nodes['素白艺术™_-_subycnvip'].geometry} material={materials.PaletteMaterial002} position={[-2.372, 15.102, -2.263]} rotation={[-0.834, -0.414, -1.988]} scale={0.037} />
      </group>
    </group>
  )
}

useGLTF.preload('/LOST_cut2_v6-transformed.glb')
