/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Scenes_B_00100.glb --transform 
Files: Scenes_B_00100.glb [279.95MB] > /Users/quan/cursor/fellou_try_v6/Scenes_B_00100-transformed.glb [5.39MB] (98%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Scenes_B_00100-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Scenes_B_00100" position={[0.61, 14.249, -5.731]} rotation={[-0.018, 0.004, 2.077]} scale={0.026}>
          <mesh name="網格003" geometry={nodes.網格003.geometry} material={materials.PaletteMaterial001} />
          <mesh name="網格003_1" geometry={nodes.網格003_1.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_2" geometry={nodes.網格003_2.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_3" geometry={nodes.網格003_3.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_4" geometry={nodes.網格003_4.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_5" geometry={nodes.網格003_5.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_6" geometry={nodes.網格003_6.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_7" geometry={nodes.網格003_7.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_8" geometry={nodes.網格003_8.geometry} material={materials.PaletteMaterial002} />
          <mesh name="網格003_9" geometry={nodes.網格003_9.geometry} material={materials.PaletteMaterial002} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Scenes_B_00100-transformed.glb')
